# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0003_auto_20161102_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='Санкт-Петербург', max_length=50),
            preserve_default=False,
        ),
    ]
