# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0004_place_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='place',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
