# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0002_remove_walk_max_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
