# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-26 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0005_auto_20161104_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='type_of_move',
            field=models.CharField(choices=[('пешая', 'пешая'), ('bikes', 'велосипедная'), ('rollers', 'на роликах'), ('other', 'другой')], max_length=30),
        ),
    ]
