# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0006_auto_20170526_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='type_of_move',
            field=models.CharField(choices=[('feet', 'пешая'), ('bikes', 'велосипедная'), ('rollers', 'на роликах'), ('other', 'другой')], max_length=30),
        ),
    ]
